apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shorty.fullname" . }}
  labels:
    {{- include "shorty.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "shorty.selectorLabels" . | nindent 6 }}
  template:
    metadata:      
      annotations:
        timestamp: {{ now | date "20060102150405" | quote}}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "shorty.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "shorty.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: 
            - name: SHORTY_DB
              value: "{{ .Values.shorty.mongo.databaseName}}"
            - name: SHORTY_COLLECTION
              value: "{{ .Values.shorty.mongo.collectionName}}"
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "shorty.fullname" . }}
                  key: mongo-uri
            {{- if .Values.shorty.production }}
            - name: GIN_MODE
              value: "release"
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /check/something
              port: http
          readinessProbe:
            httpGet:
              path: /check/something
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
