apiVersion: v1
kind: Secret
metadata:
  name: {{ template "shorty.fullname" . }}
  labels:
    {{- include "shorty.labels" . | nindent 4 }}  
type: Opaque
data:
  {{- /*from https://github.com/helm/charts/blob/master/stable/rocketchat/templates/secret.yaml */ -}}
  {{- $fullname := include "shorty.mongodb.fullname" . -}}
  {{- /*TODO: Setup a propper user with read/write access to the .Values.shorty.mongo.db_name database and use that instead of root */ -}}
  {{- /*$username := required "Please specify a MongoDB username" .Values.mongodb.auth.username */ -}}
  {{- /*$password := required "Please specify a MongoDB password" .Values.mongodb.auth.password */ -}}  
  {{- $username := "root" }}
  {{- $password := required "Please specify a MongoDB root password" .Values.mongodb.auth.rootPassword }}
  {{- $dbname := required "Please specify a MongoDB auth database" .Values.mongodb.auth.database }}
  {{- $port := .Values.mongodb.service.port }}              
  mongo-uri: {{ printf "mongodb://%s:%s@%s:%.0f/%s" $username $password $fullname $port $dbname | b64enc | quote }}